name: PR Merged Thanks

on:
  pull_request:
    types: [closed]

jobs:
  thank-you:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Thank contributor
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const author = pr.user.login;
            const body = `Thanks for your contribution, @${author}! 🎉\n\n` +
              `Your pull request has been merged. We appreciate your time and effort!`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body,
            });
